### ISSUE TITLE
[Test] Test program always return status 0.

### ISSUE THREAD

**Issue by lshqqytiger** [sdbx/Utils#19]
https://github.com/sdbx/Utils/blob/f0dc6da1ce0266f6379c638ca38111c1f3eb4785/test/test.c#L187

GitHub Actions can not catch "failed to pass test" as the test program always return 0.

https://github.com/sdbx/Utils/actions/runs/9516330154/job/26232397647

**Comment by logic-finder** [comment]
So `test` needs to return a non-zero value if test case(s) should fail?

**Comment by lshqqytiger** [comment]
Yes. For example, [this run](https://github.com/sdbx/Utils/actions/runs/9516330154/job/26232397647) should fail.
